### PR TITLE
[MAINTENANCE] issue-28: Support latest(3.12) version of Python

### PR DESCRIPTION
**Pull request by ChillarAnand**
## Description

Currently, ingen is failing to run on latest python 3.12.

## Changes Made

Updated dependencies.
Updated docs.

## Definition of Done

Before submitting this pull request, please ensure that the following criteria have been met:

- [x] All automated tests have passed successfully.
- [x] All manual tests have passed successfully.
- [x] Code has been reviewed by at least one other team member.
- [x] Code has been properly documented and commented as needed.
- [x] All new and existing code adheres to our project's coding standards.
- [x] All dependencies have been added or removed from the project's README or other documentation as needed.
- [x] Any relevant documentation or help files have been updated to reflect the changes made in this pull request.
- [x] Any necessary database migrations have been run.
- [x] Any relevant UI changes have been reviewed and approved by the UI/UX team.

### CODE REVIEW

**Comment by shpiyu** [comment]
Thanks for contributing @ChillarAnand . Can you also update the language in the classifiers section of setup.py in the same PR? https://github.com/blackrock/ingen/blob/b7929e1e59125246aa3b668fd7a95fd1da17817d/setup.py#L30

**Comment by ChillarAnand** [comment]
> Thanks for contributing @ChillarAnand . Can you also update the language in the classifiers section of setup.py in the same PR?
> 
> https://github.com/blackrock/ingen/blob/b7929e1e59125246aa3b668fd7a95fd1da17817d/setup.py#L30

Updated it. Thanks, @shpiyu

**Review by shpiyu — APPROVED** [review]
Thanks for your contribution @ChillarAnand! LGTM!

**Review by swarnadhakad — APPROVED** [review]
LGTM

**Pull request merged**
